minimum_pre_commit_version: '3.5.0'

repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.3.1
    hooks:
      - id: stylua-github
        name: stylua (Lua formatter)
        files: \.lua$
        pass_filenames: true

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier
        files: \.(md|toml|yaml|yml)$

  - repo: local
    hooks:
      - id: selene
        name: selene (Lua linter)
        entry: selene --display-style quiet
        language: system
        files: \.lua$
        pass_filenames: true

      - id: vimdoc
        name: vimdoc-language-server
        entry: vimdoc-language-server check doc/
        language: system
        files: ^doc/.*\.txt$
        pass_filenames: false

      - id: nixfmt
        name: nixfmt
        entry: nixfmt --check
        language: system
        files: \.nix$
        pass_filenames: true
