vim.opt.runtimepath:prepend(vim.fn.getcwd())

local forge = require('forge')

describe('public helper ownership', function()
  it('exposes PR helpers through forge.pr', function()
    local pr = require('forge.pr')

    assert.equal(pr.pr, forge.pr)
    assert.equal(pr.review, forge.review)
    assert.equal(pr.pr_ci, forge.pr_ci)
    assert.equal(pr.create_pr, forge.create_pr)
    assert.equal(pr.current_pr, forge.current_pr)
    assert.equal(pr.pr_state, forge.pr_state)
    assert.equal(pr.set_pr_state, forge.set_pr_state)
    assert.equal(pr.clear_pr_state, forge.clear_pr_state)
  end)

  it('exposes issue helpers through forge.issue', function()
    local issue = require('forge.issue')

    assert.equal(issue.create_issue, forge.create_issue)
    assert.equal(issue.edit_issue, forge.edit_issue)
    assert.equal(issue.template_slugs, forge.template_slugs)
  end)

  it('exposes repo helpers through forge.repo', function()
    local repo = require('forge.repo')

    assert.equal(repo.repo_info, forge.repo_info)
    assert.equal(repo.file_loc, forge.file_loc)
    assert.equal(repo.remote_web_url, forge.remote_web_url)
    assert.equal(repo.scope_from_url, forge.scope_from_url)
    assert.equal(repo.scope_repo_arg, forge.scope_repo_arg)
    assert.equal(repo.scope_key, forge.scope_key)
    assert.equal(repo.current_scope, forge.current_scope)
    assert.equal(repo.remote_name, forge.remote_name)
    assert.equal(repo.remote_ref, forge.remote_ref)
  end)

  it('exposes format helpers through forge.format', function()
    local format = require('forge.format')

    assert.equal(format.format_pr, forge.format_pr)
    assert.equal(format.format_prs, forge.format_prs)
    assert.equal(format.format_issue, forge.format_issue)
    assert.equal(format.format_issues, forge.format_issues)
    assert.equal(format.format_run, forge.format_run)
    assert.equal(format.format_runs, forge.format_runs)
    assert.equal(format.format_check, forge.format_check)
    assert.equal(format.format_checks, forge.format_checks)
    assert.equal(format.format_release, forge.format_release)
    assert.equal(format.format_releases, forge.format_releases)
    assert.equal(format.format_log_line, forge.format_log_line)
    assert.equal(format.filter_checks, forge.filter_checks)
    assert.equal(format.filter_runs, forge.filter_runs)
  end)

  it('exposes review adapter helpers through forge.review', function()
    local review = require('forge.review')

    assert.equal(review.names, forge.review_adapter_names)
    assert.equal(review.register, forge.register_review_adapter)
  end)
end)
