name: luarocks-nightly

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  quality:
    uses: ./.github/workflows/quality.yaml

  publish:
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute LuaRocks specrev
        run: echo "LUAROCKS_SPECREV=$(git rev-list --count "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: scm
          specrev: ${{ env.LUAROCKS_SPECREV }}
          license: GPL-3.0
